env:
  matrix:
    - CIBW_SKIP='cp34-* cp35-* cp36-* cp37-* cp38-*'
    - CIBW_SKIP='cp27-* cp33-* cp36-* cp37-* cp38-*'
    - CIBW_SKIP='cp27-* cp33-* cp34-* cp35-*'
  global:
    CIBW_BUILD_VERBOSITY: 3

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then (brew install python || brew upgrade python) ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PYTHON_EXEC_PATH=$(which python) ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -rf $PYTHON_EXEC_PATH ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ln -s $(which python3) $PYTHON_EXEC_PATH ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python --version ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 --version ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python3-setuptools python3-dev python3-pip -y ; fi

script:
  - echo $CIBW_SKIP
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then unset CIBW_SKIP; fi
  - echo $CIBW_SKIP
  - python3 -m pip install pip setuptools -U
  - python3 -m pip install cibuildwheel==1.4.1
  - eval "buildwheel() { cibuildwheel --output-dir wheelhouse >>buildwheel.log 2>&1; }"
  - travis_wait 60 buildwheel || (tail -c 3670016 buildwheel.log && exit 1)
  - tail -c 3670016 buildwheel.log
  - ls wheelhouse
  - python3 -m pip install awscli --upgrade
  - aws s3 sync ./wheelhouse/ s3://magnitude.plasticity.ai/wheelhouse/
